// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonDialog: typeof import('./src/components/commonDialog/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    MassPopup: typeof import('./src/components/massPopup/mass-popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
  }
}

export {}
