caring:
  rabbitmq:
    # 若系统中有除了zipkin之外的地方使用了mq ，则一定不能设置成false
    enabled: false
    ip: localhost
    port: 5672
    username: caring
    password: caring

spring:
  rabbitmq:
    enabled: ${caring.rabbitmq.enabled}
    host: ${caring.rabbitmq.ip}
    port: ${caring.rabbitmq.port}
    username: ${caring.rabbitmq.username}
    password: ${caring.rabbitmq.password}
    listener:
      type: direct # simple direct
